"""Runtime identity and provenance descriptor contracts.

This service package exposes data-only references and descriptors for
Raygent-owned runtime objects. Builder and snapshot helpers live in later
SDK-RUNTIME waves; this package starts with the stable descriptor substrate.
"""

from raygent_harness.services.runtime_identity.models import (
    DEFAULT_MAX_RUNTIME_DESCRIPTOR_METADATA_CHARS,
    RUNTIME_IDENTITY_SCHEMA_VERSION,
    ArtifactDescriptor,
    EventDescriptor,
    GoalDescriptor,
    GoalRuntimeDescriptor,
    RecoveryDescriptor,
    RuntimeDescriptor,
    RuntimeIdentityValidationError,
    RuntimeLifecycleCategory,
    RuntimeLifecycleDescriptor,
    RuntimeObjectDescriptor,
    RuntimeObjectDescriptorType,
    RuntimeObjectKind,
    RuntimeObjectReference,
    RuntimePathDisclosure,
    RuntimeProvenance,
    SessionDescriptor,
    TaskDescriptor,
    TaskOutputDescriptor,
    TranscriptEntryDescriptor,
    runtime_lifecycle_category_for,
    runtime_lifecycle_descriptor_from_dict,
    runtime_lifecycle_descriptor_to_dict,
    runtime_object_descriptor_from_dict,
    runtime_object_descriptor_to_dict,
    runtime_object_reference_from_dict,
    runtime_object_reference_to_dict,
    runtime_provenance_from_dict,
    runtime_provenance_to_dict,
)

__all__ = (
    "DEFAULT_MAX_RUNTIME_DESCRIPTOR_METADATA_CHARS",
    "RUNTIME_IDENTITY_SCHEMA_VERSION",
    "ArtifactDescriptor",
    "EventDescriptor",
    "GoalDescriptor",
    "GoalRuntimeDescriptor",
    "RecoveryDescriptor",
    "RuntimeDescriptor",
    "RuntimeIdentityValidationError",
    "RuntimeLifecycleCategory",
    "RuntimeLifecycleDescriptor",
    "RuntimeObjectDescriptor",
    "RuntimeObjectDescriptorType",
    "RuntimeObjectKind",
    "RuntimeObjectReference",
    "RuntimePathDisclosure",
    "RuntimeProvenance",
    "SessionDescriptor",
    "TaskDescriptor",
    "TaskOutputDescriptor",
    "TranscriptEntryDescriptor",
    "runtime_lifecycle_category_for",
    "runtime_lifecycle_descriptor_from_dict",
    "runtime_lifecycle_descriptor_to_dict",
    "runtime_object_descriptor_from_dict",
    "runtime_object_descriptor_to_dict",
    "runtime_object_reference_from_dict",
    "runtime_object_reference_to_dict",
    "runtime_provenance_from_dict",
    "runtime_provenance_to_dict",
)
