"""Session transcript persistence substrate."""

from raygent_harness.services.transcript.models import (
    CompactBoundaryEntry,
    ContentReplacementEntry,
    SessionMetadataEntry,
    StreamEventEntry,
    TombstoneEntry,
    TranscriptDecodeError,
    TranscriptEntry,
    TranscriptEntryType,
    TranscriptMessageEntry,
    TranscriptScope,
    current_transcript_time,
    new_transcript_entry_id,
    transcript_entry_from_dict,
    transcript_entry_from_json,
    transcript_entry_to_dict,
    transcript_entry_to_json,
)
from raygent_harness.services.transcript.paths import (
    DEFAULT_TRANSCRIPT_DIR,
    resolve_transcript_base_dir,
    safe_transcript_component,
    transcript_path_for_scope,
)
from raygent_harness.services.transcript.replay import (
    SessionReplay,
    TranscriptStoreWithSidechainListing,
    content_replacement_state_from_replay,
    get_agent_transcript,
    load_all_subagent_transcripts,
    load_session_replay,
    load_subagent_transcripts,
    reconstruct_message_chain,
    replay_entries,
)
from raygent_harness.services.transcript.search import (
    TranscriptSearchCompactMode,
    TranscriptSearchMatch,
    TranscriptSearchOrder,
    TranscriptSearchRequest,
    TranscriptSearchResult,
    TranscriptSearchScope,
    TranscriptSearchService,
)
from raygent_harness.services.transcript.store import (
    JsonlTranscriptStore,
    TranscriptReadResult,
    TranscriptReadStats,
    TranscriptStore,
)

__all__ = [
    "DEFAULT_TRANSCRIPT_DIR",
    "CompactBoundaryEntry",
    "ContentReplacementEntry",
    "JsonlTranscriptStore",
    "SessionMetadataEntry",
    "SessionReplay",
    "StreamEventEntry",
    "TombstoneEntry",
    "TranscriptDecodeError",
    "TranscriptEntry",
    "TranscriptEntryType",
    "TranscriptMessageEntry",
    "TranscriptReadResult",
    "TranscriptReadStats",
    "TranscriptScope",
    "TranscriptSearchCompactMode",
    "TranscriptSearchMatch",
    "TranscriptSearchOrder",
    "TranscriptSearchRequest",
    "TranscriptSearchResult",
    "TranscriptSearchScope",
    "TranscriptSearchService",
    "TranscriptStore",
    "TranscriptStoreWithSidechainListing",
    "content_replacement_state_from_replay",
    "current_transcript_time",
    "get_agent_transcript",
    "load_all_subagent_transcripts",
    "load_session_replay",
    "load_subagent_transcripts",
    "new_transcript_entry_id",
    "reconstruct_message_chain",
    "replay_entries",
    "resolve_transcript_base_dir",
    "safe_transcript_component",
    "transcript_entry_from_dict",
    "transcript_entry_from_json",
    "transcript_entry_to_dict",
    "transcript_entry_to_json",
    "transcript_path_for_scope",
]
