"""Import contracts for docs/public_api_surface.md."""

from __future__ import annotations

import importlib
import json
import subprocess
import sys
from pathlib import Path
from types import ModuleType
from typing import cast

DOC_PATH = Path(__file__).parents[2] / "docs" / "public_api_surface.md"

DOCUMENTED_SYMBOLS: dict[str, tuple[str, ...]] = {
    "raygent_harness.sdk": (
        "RaygentCallbackHandle",
        "RaygentAgentOptions",
        "RaygentContextOptions",
        "RaygentContextProfile",
        "RaygentContextProfileOptions",
        "RaygentContextSelection",
        "RaygentFactory",
        "RaygentFactoryConfig",
        "RaygentKernelEventCallback",
        "RaygentKernelEventCallbackSink",
        "RaygentMemoryOptions",
        "RaygentModelOptions",
        "RaygentObservabilityOptions",
        "RaygentOverlay",
        "RaygentPermissionOptions",
        "RaygentPersistenceOptions",
        "RaygentPreset",
        "RaygentPresetCompatibilityError",
        "RaygentPresetDescription",
        "RaygentPresetOptions",
        "RaygentPresetResolution",
        "RaygentRuntimeHandles",
        "RaygentRunCallbacks",
        "RaygentSDKError",
        "RaygentSDKMessageCallback",
        "RaygentSDKProtocolError",
        "RaygentSDKResultCallback",
        "RaygentSession",
        "RaygentSessionBusyError",
        "RaygentSessionClosedError",
        "RaygentSessionFactory",
        "RaygentSessionOptions",
        "RaygentToolOptions",
        "RaygentToolProfile",
        "RaygentToolProfileOptions",
        "RaygentToolSelection",
        "create_raygent",
        "describe_raygent_preset",
        "list_raygent_presets",
        "resolve_raygent_preset",
    ),
    "raygent_harness.core.query_engine": (
        "QueryEngine",
        "SDKSystemInit",
        "SDKAssistantMessage",
        "SDKUserMessage",
        "SDKCompactBoundary",
        "SDKResult",
    ),
    "raygent_harness.core.config": (
        "QueryConfig",
        "SamplingParams",
        "TurnBudget",
    ),
    "raygent_harness.core.deps": ("QueryDeps",),
    "raygent_harness.core.tool": (
        "Tool",
        "ToolSpec",
        "ToolUseContext",
        "ToolResult",
        "ToolProgress",
        "ToolCallError",
        "QueryTracking",
        "build_tool",
    ),
    "raygent_harness.core.task": ("AppStateStore",),
    "raygent_harness.core.model_provider": (
        "ModelProvider",
        "UnavailableModelProvider",
        "classify_exception_by_name",
    ),
    "raygent_harness.core.model_types": (
        "TokenCountRequest",
        "TokenCountResult",
    ),
    "raygent_harness.core.messages": (
        "MessageParam",
        "user_message",
        "assistant_message",
    ),
    "raygent_harness.core.context_providers": (
        "ContextFragment",
        "ContextKind",
        "ContextProvider",
        "PostToolContextProvider",
        "context_provider_kind",
        "filter_context_providers_by_kind",
        "render_system_context",
        "render_user_context_messages",
    ),
    "raygent_harness.agents": (
        "AgentContextPolicy",
        "AgentDefinition",
        "deps_for_agent_context_policy",
    ),
    "raygent_harness.adapters.model_protocols": (
        "AnthropicMessagesAdapter",
        "OpenAIResponsesAdapter",
    ),
    "raygent_harness.adapters.model_runtime": (
        "ProviderModelCatalog",
        "ProviderModelEntry",
        "ProtocolModelProvider",
        "ProviderPayloadError",
        "ProviderRetryDecision",
        "ProviderRetryPolicy",
        "ProviderTransport",
        "ProviderTransportRequest",
        "RetryOperation",
        "capabilities_from_modalities",
        "classify_retry_decision",
        "merge_model_info",
        "merge_model_infos",
        "registry_from_catalogs",
        "should_fallback_stream_to_complete",
    ),
    "raygent_harness.context_providers.defaults": ("build_default_context_providers",),
    "raygent_harness.context_providers.environment": (
        "EnvironmentContextProvider",
        "GitCommandResult",
        "GitCommandRunner",
        "GitStatusContextProvider",
        "default_git_command_runner",
    ),
    "raygent_harness.context_providers.project_instructions": (
        "ConditionalInstructionRule",
        "ProjectInstructionConfig",
        "ProjectInstructionFile",
        "ProjectInstructionsContextProvider",
        "ReadAdjacentProjectInstructionsContextProvider",
        "discover_conditional_instruction_rules",
        "discover_project_instruction_files",
        "instruction_rule_matches_path",
        "resolve_project_instructions_for_target_path",
    ),
    "raygent_harness.context_providers.transcript_search": (
        "TranscriptSearchContextProvider",
        "TranscriptSearchQueryResolver",
    ),
    "raygent_harness.coordinator": (
        "CoordinatorRuntime",
        "CoordinatorRuntimeConfig",
        "CoordinatorRuntimeSnapshot",
        "CoordinatorRuntimeSnapshotLoadResult",
        "CoordinatorRuntimeSnapshotStore",
        "JsonCoordinatorRuntimeSnapshotStore",
        "coordinator_runtime_snapshot_from_dict",
        "coordinator_runtime_snapshot_to_dict",
    ),
    "raygent_harness.services.agent_routes": (
        "AgentRouteRecordLoadResult",
        "AgentRouteRecordStore",
        "JsonAgentRouteRecordStore",
        "normalize_agent_route_record_for_resume",
    ),
    "raygent_harness.services.runtime_recovery": (
        "RuntimeRecoveryRequest",
        "RuntimeRecoveryResult",
        "RuntimeRecoveryService",
        "RuntimeRecoveryTaskOutputStatus",
        "RuntimeRecoveryWarning",
        "RuntimeRecoveryWarningSource",
        "RuntimeRecoveryWorktreeStatus",
        "resume_runtime_session",
    ),
    "raygent_harness.services.improvement_runtime": (
        "IMPROVEMENT_RUNTIME_RECORD_SCHEMA_VERSION",
        "DEFAULT_MAX_EVIDENCE_COLLECTION_ITEMS",
        "DEFAULT_MAX_EVIDENCE_COLLECTION_EXCERPT_CHARS",
        "DEFAULT_MAX_EVIDENCE_COLLECTION_SOURCE_URI_CHARS",
        "DEFAULT_MAX_EVIDENCE_COLLECTION_ITEM_METADATA_CHARS",
        "DEFAULT_MAX_EVIDENCE_COLLECTION_TOTAL_METADATA_CHARS",
        "DEFAULT_MAX_EVIDENCE_COLLECTION_WARNINGS",
        "DEFAULT_MAX_EVIDENCE_COLLECTION_TOTAL_CHARS",
        "DEFAULT_MAX_IMPROVEMENT_RUNTIME_METADATA_CHARS",
        "DEFAULT_MAX_IMPROVEMENT_RUNTIME_PAYLOAD_REF_CHARS",
        "DEFAULT_MAX_IMPROVEMENT_RUNTIME_WARNING_CHARS",
        "DEFAULT_MAX_IMPROVEMENT_RUNTIME_WARNINGS",
        "DEFAULT_MAX_IMPROVEMENT_RUNTIME_STOP_REASON_CHARS",
        "DEFAULT_MAX_IMPROVEMENT_RUNTIME_SUMMARY_RECORDS",
        "TRANSCRIPT_SEARCH_MIN_SNIPPET_CHARS",
        "BoundedImprovementEvidenceCollection",
        "ImprovementEvidenceCollectionBounds",
        "ImprovementEvidenceCollectionRequest",
        "ImprovementEvidenceCollectionResult",
        "ImprovementEvidenceSourceAdapter",
        "TranscriptSearchImprovementEvidenceAdapter",
        "ImprovementTaskOutputReadMode",
        "ImprovementTaskOutputEvidenceTarget",
        "TaskOutputImprovementEvidenceAdapter",
        "ImprovementObservabilitySnapshot",
        "ObservabilitySnapshotImprovementEvidenceAdapter",
        "ImprovementRuntimePermissionRequirement",
        "ImprovementRuntimePermissionSummary",
        "ImprovementRuntimePermissionReport",
        "ImprovementRuntimePermissionStatus",
        "ImprovementRuntimePermissionPolicy",
        "ImprovementRuntimeObservabilityEvent",
        "ImprovementRuntimeObservabilitySink",
        "KernelEventImprovementRuntimeObserver",
        "ImprovementRecordStore",
        "ImprovementRuntimeBridge",
        "ImprovementRuntimeBridgeConfig",
        "ImprovementRuntimeChainSummary",
        "ImprovementRuntimeRecord",
        "ImprovementRuntimeRecordKind",
        "ImprovementRuntimeRecordQuery",
        "ImprovementRuntimeRequest",
        "ImprovementRuntimeTransitionResult",
        "ImprovementRuntimeTransitionStatus",
        "ImprovementRuntimeValidationError",
        "improvement_evidence_collection_result_from_dict",
        "improvement_evidence_collection_result_to_dict",
        "improvement_runtime_permission_requirement_from_dict",
        "improvement_runtime_permission_requirement_to_dict",
        "improvement_runtime_permission_summary_from_dict",
        "improvement_runtime_permission_summary_to_dict",
        "improvement_runtime_permission_report_from_dict",
        "improvement_runtime_permission_report_to_dict",
        "improvement_runtime_permission_report_to_summary",
        "improvement_runtime_observability_event_from_dict",
        "improvement_runtime_observability_event_from_result",
        "improvement_runtime_observability_event_to_dict",
        "improvement_runtime_chain_summary_from_dict",
        "improvement_runtime_chain_summary_to_dict",
        "improvement_runtime_record_from_dict",
        "improvement_runtime_record_to_dict",
        "validate_improvement_evidence_collection",
    ),
    "raygent_harness.services.file_media": (
        "PDF_MAX_EXTRACT_SIZE_BYTES",
        "PDF_PAGE_RENDER_DPI",
        "CommandBackedPdfDocumentService",
        "CommandResult",
        "CommandRunner",
        "FileMediaClassification",
        "NOTEBOOK_LARGE_OUTPUT_THRESHOLD_CHARS",
        "NOTEBOOK_MAX_PROCESSED_BYTES",
        "NOTEBOOK_MAX_RAW_BYTES",
        "NOTEBOOK_OUTPUT_TEXT_MAX_CHARS",
        "NotebookCellOutput",
        "NotebookCellSource",
        "NotebookOutputImage",
        "NotebookParseResult",
        "NotebookServiceError",
        "NotebookServiceErrorReason",
        "PdfDocumentService",
        "PdfExtractedPage",
        "PdfPageCountResult",
        "PdfPageExtractionRequest",
        "PdfPageExtractionResult",
        "PdfServiceError",
        "PdfServiceErrorReason",
        "SubprocessCommandRunner",
        "classify_file_extension",
        "classify_file_media",
        "classify_magic_bytes",
        "detect_supported_image_media_type",
        "extension_for_path",
        "is_blocked_device_path",
        "notebook_cells_to_content",
        "notebook_cells_to_json",
        "parse_notebook_content",
    ),
    "raygent_harness.services.task_notification_replay": (
        "TaskNotificationReplayCoordinator",
        "TaskNotificationReplayRecord",
        "TaskNotificationReplayResult",
        "TaskNotificationReplaySource",
        "remote_agent_restore_replay_record",
        "remote_agent_terminal_dedupe_key",
        "replay_task_notifications",
    ),
    "raygent_harness.tools": (
        "NOTEBOOK_EDIT_MAX_RESULT_SIZE_CHARS",
        "NOTEBOOK_EDIT_PROMPT",
        "NOTEBOOK_EDIT_TOOL_NAME",
        "NotebookEditInput",
        "NotebookEditResult",
        "NotebookEditToolError",
        "build_notebook_edit_tool",
        "create_notebook_edit_catalog_provider",
        "parse_notebook_cell_id",
    ),
    "raygent_harness.services.transcript": (
        "TranscriptSearchCompactMode",
        "TranscriptSearchMatch",
        "TranscriptSearchOrder",
        "TranscriptSearchRequest",
        "TranscriptSearchResult",
        "TranscriptSearchScope",
        "TranscriptSearchService",
    ),
    "raygent_harness.improvement": (
        "DEFAULT_IMPROVEMENT_MODEL_GENERATOR_SYSTEM_PROMPT",
        "DEFAULT_MAX_EVALUATION_OUTPUT_EXCERPT_CHARS",
        "DEFAULT_MAX_MATERIALIZATION_CHANGED_FILES",
        "DEFAULT_MAX_MATERIALIZATION_METADATA_CHARS",
        "DEFAULT_MAX_MATERIALIZATION_OPERATIONS",
        "DEFAULT_MAX_MATERIALIZATION_PATH_CHARS",
        "DEFAULT_MAX_MATERIALIZATION_TEXT_CHARS",
        "DEFAULT_MAX_OUTCOME_BLOCKERS",
        "DEFAULT_MAX_OUTCOME_BLOCKER_CHARS",
        "DEFAULT_MAX_OUTCOME_METADATA_CHARS",
        "DEFAULT_MAX_OUTCOME_SUMMARY_CHARS",
        "DEFAULT_MAX_ARCHIVE_ARTIFACT_REFERENCES",
        "DEFAULT_MAX_ARCHIVE_ARTIFACT_REFERENCE_CHARS",
        "DEFAULT_MAX_ARCHIVE_FAILURE_SYMPTOMS",
        "DEFAULT_MAX_ARCHIVE_FAILURE_SYMPTOM_CHARS",
        "DEFAULT_MAX_ARCHIVE_STORAGE_KEY_CHARS",
        "DEFAULT_MAX_ARCHIVE_STORAGE_KIND_CHARS",
        "DEFAULT_MAX_ARCHIVE_RECORD_METADATA_CHARS",
        "DEFAULT_MAX_PROMOTION_REF_CHARS",
        "DEFAULT_MAX_PROMOTION_KIND_CHARS",
        "DEFAULT_MAX_PROMOTED_FILES",
        "DEFAULT_MAX_PROMOTED_FILE_CHARS",
        "DEFAULT_MAX_PROMOTION_SUMMARY_CHARS",
        "DEFAULT_MAX_PROMOTION_RECORD_METADATA_CHARS",
        "DEFAULT_MAX_VERIFICATION_CHECKS",
        "DEFAULT_MAX_VERIFICATION_CHECK_NAME_CHARS",
        "DEFAULT_MAX_VERIFICATION_INSTRUCTION_CHARS",
        "DEFAULT_MAX_VERIFICATION_REF_CHARS",
        "DEFAULT_MAX_VERIFICATION_RUNNER_KIND_CHARS",
        "DEFAULT_MAX_VERIFICATION_RECORD_METADATA_CHARS",
        "BoundedImprovementEvidence",
        "ImprovementDiagnosis",
        "ImprovementEvaluationCheck",
        "ImprovementEvaluationPlan",
        "ImprovementEvidence",
        "ImprovementEvidenceBounds",
        "ImprovementEvidenceSource",
        "ImprovementEvidenceValidationError",
        "ImprovementGateDecision",
        "ImprovementGateError",
        "ImprovementGateEvaluation",
        "ImprovementGateKind",
        "ImprovementGatePolicy",
        "ImprovementGateResult",
        "ImprovementGateStatus",
        "ImprovementGateValidationError",
        "ImprovementModelGenerator",
        "ImprovementModelGeneratorError",
        "ImprovementPatchCandidateEvaluation",
        "ImprovementPatchCandidateEvaluationDecision",
        "ImprovementPatchCandidateEvaluationKind",
        "ImprovementPatchCandidateEvaluationResult",
        "ImprovementPatchCandidateEvaluationStatus",
        "ImprovementPatchCandidateArchiveApproval",
        "ImprovementPatchCandidateArchiveDecision",
        "ImprovementPatchCandidateArchiveDecisionPolicy",
        "ImprovementPatchCandidateArchiveError",
        "ImprovementPatchCandidateArchiveRecord",
        "ImprovementPatchCandidateArchiveRequest",
        "ImprovementPatchCandidateArchiveStatus",
        "ImprovementPatchCandidateArchiveStore",
        "ImprovementPatchCandidateArchiveStoreResult",
        "ImprovementPatchCandidateArchiveValidationError",
        "ImprovementPatchCandidateArchiver",
        "ImprovementPatchCandidatePromotionApproval",
        "ImprovementPatchCandidatePromotionRequest",
        "ImprovementPatchCandidatePromotionResult",
        "ImprovementPatchCandidatePromoter",
        "ImprovementPatchCandidatePromotionRecord",
        "ImprovementPatchCandidatePromotionService",
        "ImprovementPatchCandidatePromotionStatus",
        "ImprovementPatchCandidatePromotionError",
        "ImprovementPatchCandidatePromotionValidationError",
        "ImprovementPatchCandidateVerificationCheck",
        "ImprovementPatchCandidateVerificationCheckResult",
        "ImprovementPatchCandidateVerificationCheckSource",
        "ImprovementPatchCandidateVerificationError",
        "ImprovementPatchCandidateVerificationPlan",
        "ImprovementPatchCandidateVerificationPlanStatus",
        "ImprovementPatchCandidateVerificationPlanner",
        "ImprovementPatchCandidateVerificationApproval",
        "ImprovementPatchCandidateVerificationRecord",
        "ImprovementPatchCandidateVerificationRequest",
        "ImprovementPatchCandidateVerificationResult",
        "ImprovementPatchCandidateVerificationService",
        "ImprovementPatchCandidateVerificationStatus",
        "ImprovementPatchCandidateVerificationValidationError",
        "ImprovementPatchCandidateVerifier",
        "ImprovementPatchCandidateError",
        "ImprovementPatchCandidateMaterialization",
        "ImprovementPatchCandidateMaterializationApproval",
        "ImprovementPatchCandidateMaterializationError",
        "ImprovementPatchCandidateMaterializationStatus",
        "ImprovementPatchCandidateMaterializationValidationError",
        "ImprovementPatchCandidateMaterializer",
        "ImprovementPatchCandidateOutcome",
        "ImprovementPatchCandidateOutcomeDecision",
        "ImprovementPatchCandidateOutcomeError",
        "ImprovementPatchCandidateOutcomePolicy",
        "ImprovementPatchCandidateOutcomeReason",
        "ImprovementPatchCandidateOutcomeValidationError",
        "ImprovementPatchCandidatePlan",
        "ImprovementPatchCandidatePlanner",
        "ImprovementPatchCandidateStatus",
        "ImprovementPatchCandidateValidationError",
        "ImprovementPatchCandidateWorktreeAllocation",
        "ImprovementPatchCandidateWorktreeAllocator",
        "ImprovementPatchCandidateWorktreeApproval",
        "ImprovementPatchCandidateWorktreeError",
        "ImprovementPatchCandidateWorktreeStatus",
        "ImprovementPatchCandidateWorktreeValidationError",
        "ImprovementPatchMaterializationRequest",
        "ImprovementPatchMaterializationResult",
        "ImprovementPatchMaterializer",
        "ImprovementPatchOperation",
        "ImprovementPatchOperationKind",
        "ImprovementProposal",
        "ImprovementProposalGenerator",
        "ImprovementProposalRequest",
        "ImprovementRequiredPermission",
        "ImprovementRun",
        "ImprovementRunStatus",
        "ImprovementService",
        "ImprovementServiceError",
        "ImprovementTarget",
        "ImprovementTargetKind",
        "ImprovementValidationError",
        "improvement_diagnosis_from_dict",
        "improvement_diagnosis_to_dict",
        "improvement_evaluation_check_from_dict",
        "improvement_evaluation_check_to_dict",
        "improvement_evaluation_plan_from_dict",
        "improvement_evaluation_plan_to_dict",
        "improvement_evidence_from_dict",
        "improvement_evidence_text_chars",
        "improvement_evidence_to_dict",
        "improvement_gate_evaluation_from_dict",
        "improvement_gate_evaluation_to_dict",
        "improvement_gate_result_from_dict",
        "improvement_gate_result_to_dict",
        "improvement_patch_candidate_plan_from_dict",
        "improvement_patch_candidate_plan_to_dict",
        "improvement_patch_candidate_archive_decision_from_dict",
        "improvement_patch_candidate_archive_decision_to_dict",
        "improvement_patch_candidate_archive_record_from_dict",
        "improvement_patch_candidate_archive_record_to_dict",
        "improvement_patch_candidate_archive_request_from_dict",
        "improvement_patch_candidate_archive_request_to_dict",
        "improvement_patch_candidate_archive_store_result_from_dict",
        "improvement_patch_candidate_archive_store_result_to_dict",
        "improvement_patch_candidate_promotion_request_from_dict",
        "improvement_patch_candidate_promotion_request_to_dict",
        "improvement_patch_candidate_promotion_result_from_dict",
        "improvement_patch_candidate_promotion_result_to_dict",
        "improvement_patch_candidate_promotion_record_from_dict",
        "improvement_patch_candidate_promotion_record_to_dict",
        "improvement_patch_candidate_verification_check_from_dict",
        "improvement_patch_candidate_verification_check_result_from_dict",
        "improvement_patch_candidate_verification_check_result_to_dict",
        "improvement_patch_candidate_verification_check_to_dict",
        "improvement_patch_candidate_verification_plan_from_dict",
        "improvement_patch_candidate_verification_plan_to_dict",
        "improvement_patch_candidate_verification_record_from_dict",
        "improvement_patch_candidate_verification_record_to_dict",
        "improvement_patch_candidate_verification_record_to_evaluation",
        "improvement_patch_candidate_verification_request_from_dict",
        "improvement_patch_candidate_verification_request_to_dict",
        "improvement_patch_candidate_verification_result_from_dict",
        "improvement_patch_candidate_verification_result_to_dict",
        "improvement_patch_candidate_evaluation_from_dict",
        "improvement_patch_candidate_evaluation_result_from_dict",
        "improvement_patch_candidate_evaluation_result_to_dict",
        "improvement_patch_candidate_evaluation_to_dict",
        "improvement_patch_candidate_materialization_from_dict",
        "improvement_patch_candidate_materialization_to_dict",
        "improvement_patch_candidate_outcome_from_dict",
        "improvement_patch_candidate_outcome_to_dict",
        "improvement_patch_candidate_worktree_allocation_from_dict",
        "improvement_patch_candidate_worktree_allocation_to_dict",
        "improvement_patch_operation_from_dict",
        "improvement_patch_operation_to_dict",
        "improvement_proposal_from_dict",
        "improvement_proposal_to_dict",
        "improvement_run_from_dict",
        "improvement_run_to_dict",
        "improvement_target_from_dict",
        "improvement_target_to_dict",
        "validate_bounded_improvement_evidence",
    ),
}

DOCUMENTED_MODULES: tuple[str, ...] = (
    "raygent_harness.sdk",
    "raygent_harness.core.model_types",
    "raygent_harness.core.permissions",
    "raygent_harness.core.permission_engine",
    "raygent_harness.core.tool_hooks",
    "raygent_harness.core.stop_hooks",
    "raygent_harness.core.observability",
    "raygent_harness.core.context_providers",
    "raygent_harness.tools",
    "raygent_harness.context_providers.defaults",
    "raygent_harness.context_providers.environment",
    "raygent_harness.context_providers.project_instructions",
    "raygent_harness.context_providers.transcript_search",
    "raygent_harness.memdir",
    "raygent_harness.services.extract_memories",
    "raygent_harness.services.team_memory_sync",
    "raygent_harness.services.transcript",
    "raygent_harness.services.task_output",
    "raygent_harness.improvement",
    "raygent_harness.services.worktree",
    "raygent_harness.services.remote_agent",
    "raygent_harness.services.agent_routes",
    "raygent_harness.services.runtime_recovery",
    "raygent_harness.services.improvement_runtime",
    "raygent_harness.services.task_notification_replay",
    "raygent_harness.services.mcp",
    "raygent_harness.adapters.model_protocols",
    "raygent_harness.adapters.model_runtime",
    "raygent_harness.core.child_query",
    "raygent_harness.core.tool_execution",
    "raygent_harness.core.tool_orchestration",
    "raygent_harness.core.streaming_tool_executor",
    "raygent_harness.coordinator",
    "raygent_harness.agents",
    "raygent_harness.skills",
    "raygent_harness.services.compact",
    "raygent_harness.services.handoff",
    "raygent_harness.services.file_media",
)


def _import_module(module_name: str) -> ModuleType:
    return importlib.import_module(module_name)


def _symbol_appears_in_doc(doc_text: str, symbol_name: str) -> bool:
    return f"`{symbol_name}`" in doc_text or f"`{symbol_name}(" in doc_text


def test_documented_symbol_imports_are_available() -> None:
    doc_text = DOC_PATH.read_text()

    for module_name, symbol_names in DOCUMENTED_SYMBOLS.items():
        assert module_name in doc_text
        module = _import_module(module_name)
        for symbol_name in symbol_names:
            assert _symbol_appears_in_doc(doc_text, symbol_name)
            assert hasattr(module, symbol_name), f"{module_name}.{symbol_name} is documented"


def test_sdk_all_matches_documented_contract() -> None:
    module = _import_module("raygent_harness.sdk")
    exported = cast(tuple[str, ...], module.__all__)

    assert set(exported) == set(DOCUMENTED_SYMBOLS["raygent_harness.sdk"])


def test_public_api_doc_describes_preset_precedence_contract() -> None:
    doc_text = DOC_PATH.read_text()

    for expected in (
        "`RaygentToolOptions.tools` overrides preset tool defaults",
        "`RaygentContextOptions.context` overrides preset context defaults",
        "`RaygentPersistenceOptions.transcript_store` overrides preset transcript",
        "`RaygentPersistenceOptions.task_output_dir` overrides preset task-output",
        "explicit permission surface",
        "`RaygentPresetResolution`",
    ):
        assert expected in doc_text


def test_public_api_doc_describes_improvement_boundary() -> None:
    doc_text = DOC_PATH.read_text()

    for expected in (
        "`raygent_harness.improvement`",
        "proposal-only, non-mutating improvement records",
        "gate/evaluation records are supplied-result policy checks",
        "optional model-backed proposal generator uses a tool-free",
        "data-only patch candidate plans",
        "status is `planned` only",
        "isolated worktree allocation requires explicit call-time approval",
        "allocation status is `allocated` only",
        "injected `WorktreeManager`",
        "approval is not serialized as durable reusable authority",
        "materialization uses an injected `ImprovementPatchMaterializer`",
        "service-owned `patch_digest`",
        "supplied evaluation results include `required`",
        "data-only outcome/archive-decision records",
        "outcome decisions",
        "not promotion authority",
        "archive decisions are recommendations",
        "injected archive persistence only",
        "caller-owned `ImprovementPatchCandidateArchiveStore`",
        "service-owned `archive_digest`",
        "injected promotion-attempt recording only",
        "caller-owned `ImprovementPatchCandidatePromoter`",
        "`status == \"promotion_recorded\"`",
        "service-owned `promotion_digest`",
        "verification planning records derive bounded checks",
        "injected verifier protocol",
        "caller-owned `ImprovementPatchCandidateVerifier`",
        "`status == \"verification_recorded\"`",
        "service-owned `verification_digest`",
        "allowed_changed_files",
        "`status == \"verification_planned\"`",
        "optional runtime bridge contracts for explicit caller invocation only",
        "versioned immutable improvement-chain envelopes",
        "bounded recovery-summary records",
        "injectable evidence source adapters",
        "bounded `TranscriptSearchImprovementEvidenceAdapter`",
        "`TaskOutputImprovementEvidenceAdapter` requires explicit",
        "`ImprovementTaskOutputEvidenceTarget` records",
        "`ObservabilitySnapshotImprovementEvidenceAdapter` consumes caller-supplied",
        "`ImprovementObservabilitySnapshot` records",
        "rejects raw-looking snapshot fields",
        "redaction markers",
        "`ImprovementRuntimePermissionPolicy` produces advisory",
        "full reports are return values",
        "`ImprovementRuntimePermissionSummary` is the only permission shape",
        "`KernelEventImprovementRuntimeObserver`",
        "`content_policy=\"metadata_only\"`",
        "`ImprovementRuntimeBridge` is inert unless a caller constructs",
        "return `completed`, `blocked`, or `not_enabled`",
        "does not modify `QueryEngine`",
        "does not invoke Raygent tools",
        "does not ship a concrete filesystem writer",
        "ship a concrete archive backend",
        "ship a concrete Git promoter",
        "search archives",
        "`ModelProvider.complete(...)`",
        "`ModelRequest.tools == ()`",
        "does not mutate files",
        "materialize patches",
        "execute shell commands",
        "call models",
        "request permissions",
        "product `/goal` commands",
    ):
        assert expected in doc_text


def test_documented_module_imports_are_available() -> None:
    doc_text = DOC_PATH.read_text()

    for module_name in DOCUMENTED_MODULES:
        assert module_name in doc_text
        assert _import_module(module_name)


def test_top_level_package_remains_intentionally_minimal() -> None:
    code = (
        "import json, raygent_harness; "
        "names = sorted("
        "name for name in raygent_harness.__dict__ "
        "if name == '__version__' or not name.startswith('_')"
        "); "
        "print(json.dumps(names))"
    )
    completed = subprocess.run(
        [sys.executable, "-c", code],
        check=True,
        capture_output=True,
        text=True,
    )

    public_names = cast(list[str], json.loads(completed.stdout))
    assert public_names == ["__version__"]
